# Generated by Django 4.1.2 on 2023-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_flavorprofile_product_flavor_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavorprofile',
            name='items',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
