# Generated by Django 4.1.2 on 2023-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_flavorprofile_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavorprofile',
            name='items',
        ),
        migrations.AddField(
            model_name='flavorprofile',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
