# Generated by Django 4.1.2 on 2023-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_flavorprofile_items_flavorprofile_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorprofile',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='product(s)'),
        ),
    ]
