# Generated by Django 4.1.2 on 2023-02-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_flavorprofile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavor_profiles',
        ),
    ]
