# Generated by Django 4.1.2 on 2023-03-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
