# Generated by Django 4.1.2 on 2023-03-01 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('history_page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='History Page ID')),
                ('background_img', models.URLField(max_length=2049, verbose_name='Background Image')),
                ('history_title', models.TextField(max_length=1000, verbose_name='History Title')),
                ('history_summary', models.TextField(max_length=1000, verbose_name='History Summary')),
                ('top_left_video_title', models.TextField(max_length=1000, verbose_name='Top Left Video Title')),
                ('top_left_video_link', models.URLField(max_length=2049, verbose_name='Top Left Video Link')),
                ('top_right_video_title', models.TextField(max_length=1000, verbose_name='Top Right Video Title')),
                ('top_right_video_link', models.URLField(max_length=2049, verbose_name='Top Right Video Link')),
                ('bottom_left_video_title', models.TextField(max_length=1000, verbose_name='Bottom Left Video Title')),
                ('bottom_left_video_link', models.URLField(max_length=2049, verbose_name='Bottom Left Video Link')),
                ('bottom_right_video_title', models.TextField(max_length=1000, verbose_name='Bottom Right Video Title')),
                ('bottom_right_video_link', models.URLField(max_length=2049, verbose_name='Bottom Right Video Link')),
            ],
            options={
                'verbose_name_plural': 'History Page',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('home_page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Home Page ID')),
                ('left_img', models.URLField(max_length=2049, verbose_name='Left Image Link')),
                ('right_img', models.URLField(max_length=2049, verbose_name='Right Image Link')),
                ('right_img_title', models.TextField(max_length=100, verbose_name='Right Image Title')),
                ('right_img_description', models.TextField(max_length=1000, verbose_name='Right Image Description')),
                ('bottom_img', models.URLField(max_length=2049, verbose_name='Bottom Image Link')),
                ('mission_statement', models.TextField(max_length=1000, verbose_name='Mission Statement Text')),
            ],
            options={
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('news_page_content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='News Page ID')),
                ('background_img', models.URLField(max_length=2049, verbose_name='Background Image')),
            ],
            options={
                'verbose_name_plural': 'News Page',
            },
        ),
    ]
