# Generated by Django 4.1.2 on 2023-03-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypage',
            old_name='history_page_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='home_page_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='news_page_content_id',
            new_name='id',
        ),
    ]
