# Generated by Django 4.1.2 on 2023-02-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
