# Generated by Django 4.1.2 on 2023-02-26 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('news_post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='news_post_id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(max_length=5000, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
