# Generated by Django 4.1.2 on 2023-03-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='news_post_id',
            new_name='id',
        ),
    ]
