# Generated by Django 4.1.2 on 2023-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(editable=False, verbose_name='user role'),
        ),
    ]
