# Generated by Django 4.1.2 on 2023-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_subscribed'),
        ),
    ]
