# Generated by Django 4.1.2 on 2023-02-12 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(verbose_name='user role'),
        ),
    ]
