# Generated by Django 4.1.2 on 2023-02-26 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_id_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users(s)')),
            ],
        ),
    ]
