# Generated by Django 4.1.2 on 2023-03-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
