# Generated by Django 4.1.2 on 2023-03-05 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 5, 10, 19, 1587)),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 5, 10, 19, 2803)),
        ),
    ]
