"""
Django settings for tipforthetrip project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import dj_database_url

from .uniform import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

IS_HEROKU = "DYNO" in os.environ 

SECRET_KEY = os.getenv('DJANGO_SECRET')

# if 'SECRET_KEY' in os.environ:
    # SECRET_KEY = os.getenv("SECRET_KEY")


# Generally avoid wildcards(*). However since Heroku router provides hostname validation it is ok
# if IS_HEROKU:
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'tipforthetrip-backend.herokuapp.com']
# else:
    # ALLOWED_HOSTS = []


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    },
}

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
